window.TEKAGON_PUBLIC_CONFIG = window.TEKAGON_PUBLIC_CONFIG || {
  API_URL: '',
  FIREBASE_API_KEY: '',
  FIREBASE_AUTH_DOMAIN: '',
  FIREBASE_PROJECT_ID: '',
  FIREBASE_STORAGE_BUCKET: '',
  FIREBASE_MESSAGING_SENDER_ID: '',
  FIREBASE_APP_ID: '',
  FIREBASE_MEASUREMENT_ID: '',
  INDEX_FIREBASE_API_KEY: '',
  INDEX_FIREBASE_AUTH_DOMAIN: '',
  INDEX_FIREBASE_PROJECT_ID: '',
  INDEX_FIREBASE_STORAGE_BUCKET: '',
  INDEX_FIREBASE_MESSAGING_SENDER_ID: '',
  INDEX_FIREBASE_APP_ID: '',
  INDEX_FIREBASE_MEASUREMENT_ID: '',
  CLOUDINARY_CLOUD_NAME: '',
  CLOUDINARY_UPLOAD_PRESET: ''
};
